upstream monitoring {
  server grafana:3000;  
  keepalive_timeout 60s;    
}

server {
  listen 443 default_server;
  server_name _;


  location /monitoring/ {
    proxy_pass http://monitoring;
  }
}