{
 "title": "Прикладные",
 "time": { "from": "2026-09-30T19:41:59.000Z", "to": "2026-10-01T19:41:59.000Z" },
 "panels": [
  {
   "title": "Заявки по статусам и приоритеам",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  status,\r\n  priority,\r\n  COUNT(*) as \"Количество\"\r\n\r\nFROM \"MaintenanceRequests\" mr\r\nGROUP BY mr.status, mr.priority\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Заявки по приоритетам",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  priority,\r\n  COUNT(*) as \"Количество\"\r\nFROM \"MaintenanceRequests\" mr\r\nGROUP BY mr.priority\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Заявки по статусам",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  status,\r\n  COUNT(*) as \"Количество\"\r\n\r\nFROM \"MaintenanceRequests\" mr\r\nGROUP BY mr.status\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Среднее время закрытие заявок по площадке",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ROUND(\r\n    AVG(EXTRACT(EPOCH FROM (rsh.\"createdAt\" - mr.\"plannedAt\")) / 3600.0)::numeric,\r\n    2\r\n  ) AS \"avg hours\",\r\n  s.\"code\"\r\nFROM \"MaintenanceRequests\" mr\r\nJOIN \"Equipment\" e ON e.id = mr.\"equipmentId\"\r\nJOIN \"Sites\" s ON s.id = e.\"siteId\"\r\nJOIN \"RequestStatusHistories\" rsh ON rsh.\"requestId\" = mr.id\r\nWHERE mr.status = 'done'\r\n  AND rsh.\"newStatus\" = 'done'\r\nGROUP BY s.\"code\"\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Нагрузка на оборудование",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 15, "x": 8, "y": 6 },
   "targets": [
    {
     "rawSql": " SELECT \r\n    e.name,\r\n    COUNT(mr.id) as \"Всего заявок\",\r\n    COUNT(CASE WHEN mr.status = 'done' THEN 1 END) as \"Завершенных заявок\"\r\n  FROM \"Equipment\" as e\r\n  LEFT JOIN \"EquipmentPassports\" as ep \r\n    ON e.id = ep.\"equipmentId\"\r\n  LEFT JOIN \"MaintenanceRequests\" as mr \r\n    ON e.id = mr.\"equipmentId\"\r\n  LEFT JOIN \"RequestAssignees\" as ra \r\n    ON ra.\"requestId\" = mr.id\r\n  GROUP BY e.id\r\n  HAVING COUNT(CASE WHEN mr.status = 'done' THEN 1 END) >= 1"
    }
   ]
  },
  {
   "title": "Количество просроченных работ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \r\n  COUNT(*)\r\nFROM \"MaintenanceRequests\" mr\r\nWHERE mr.status IN ('new', 'in_progress')\r\n  AND mr.\"plannedAt\" < now()\r\nORDER BY 1"
    }
   ]
  }
 ]
}