{
 "title": "Технические",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Интенсивность запросов (в минуту)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(\"createdAt\", '1m') AS time,\r\n  COUNT(*)::float / 60       AS \"RPS\"\r\nFROM \"HttpMetrics\" \r\nWHERE $__timeFilter(\"createdAt\")\r\nGROUP BY 1\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Доля 4xx и 5xx",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(\"createdAt\", '1m') AS time,\r\n  100.0 * SUM(CASE WHEN \"statusCode\" BETWEEN 400 AND 499 THEN 1 ELSE 0 END) / COUNT(*) AS \"4xx %\",\r\n  100.0 * SUM(CASE WHEN \"statusCode\" >= 500 THEN 1 ELSE 0 END)             / COUNT(*) AS \"5xx %\"\r\nFROM \"HttpMetrics\" \r\nWHERE $__timeFilter(\"createdAt\")\r\nGROUP BY 1\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Время ответа (p50/p95/p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(\"createdAt\", '1m') AS time,\r\n  percentile_cont(0.50) WITHIN GROUP (ORDER BY \"durationMs\") AS \"p50\",\r\n  percentile_cont(0.95) WITHIN GROUP (ORDER BY \"durationMs\") AS \"p95\",\r\n  percentile_cont(0.99) WITHIN GROUP (ORDER BY \"durationMs\") AS \"p99\"\r\nFROM \"HttpMetrics\" \r\nWHERE $__timeFilter(\"createdAt\")\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Доступность сервиса",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(\"createdAt\", '1m') AS time,\r\n  100.0 * SUM(CASE WHEN \"statusCode\" < 500 THEN 1 ELSE 0 END) \r\n  / NULLIF(COUNT(*), 0) AS \"Uptime %\"\r\nFROM \"HttpMetrics\" \r\nWHERE $__timeFilter(\"createdAt\")\r\nGROUP BY 1\r\nORDER BY 1;"
    }
   ]
  }
 ]
}