apiVersion: 1
contactPoints:
    - orgId: 1
      name: API_WEBHOOK
      receivers:
        - uid: dfzwxjdwaocn5c
          type: webhook
          settings:
            httpMethod: POST
            url: http://app:3000/monitoring
          disableResolveMessage: false
